# Generated by Django 5.1 on 2024-11-15 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='EstructuraModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matriula', models.CharField(max_length=100, null=True)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('ftrab', models.CharField(max_length=250, null=True)),
                ('ffirma', models.CharField(max_length=250, null=True)),
                ('fnac', models.CharField(max_length=30, null=True)),
                ('categoria', models.CharField(max_length=100, null=True)),
                ('adsc_act', models.CharField(max_length=100, null=True)),
                ('adsc_ant', models.CharField(max_length=100, null=True)),
                ('turno', models.CharField(max_length=100, null=True)),
                ('domicilio', models.CharField(max_length=150, null=True)),
                ('colonia', models.CharField(max_length=100, null=True)),
                ('municipio', models.CharField(max_length=100, null=True)),
                ('seccional', models.CharField(max_length=10, null=True)),
                ('num_cel', models.CharField(max_length=10, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('Resp_100', models.CharField(max_length=100, null=True)),
                ('Resp_10', models.CharField(max_length=100, null=True)),
                ('part_trab', models.CharField(max_length=250, null=True)),
                ('inf_adic', models.CharField(max_length=250, null=True)),
                ('descansos', models.CharField(max_length=50, null=True)),
                ('vac_prog', models.CharField(max_length=150, null=True)),
                ('servicio', models.CharField(max_length=150, null=True)),
                ('promocion', models.CharField(max_length=150, null=True)),
                ('movilizacion', models.CharField(max_length=150, null=True)),
                ('asis_reu', models.CharField(max_length=150, null=True)),
                ('voto_25Sept', models.CharField(max_length=150, null=True)),
                ('engrupo', models.CharField(max_length=150, null=True)),
                ('estatus', models.CharField(max_length=150, null=True)),
                ('inf_admin', models.CharField(max_length=250, null=True)),
                ('mi_resp', models.CharField(max_length=100, null=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'estructuratbl',
            },
        ),
    ]
